import type { HighlightTemplate } from "./types";

// ── 8 templates ported from iOS TemplateLibrary ──

export const TEMPLATES: HighlightTemplate[] = [
  {
    id: "adventure",
    name: "Adventure",
    icon: "Mountain",
    description: "Epic outdoor moments with cinematic flair",
    suggestedFilter: "Vibrant",
    suggestedCaptionStyle: "Bold",
    suggestedMusicMood: "Epic",
    colorAccent: "#F59E0B",
  },
  {
    id: "foodie",
    name: "Foodie",
    icon: "UtensilsCrossed",
    description: "Warm, appetizing food highlights",
    suggestedFilter: "Warm",
    suggestedCaptionStyle: "Classic",
    suggestedMusicMood: "Chill",
    colorAccent: "#EF4444",
  },
  {
    id: "fitness",
    name: "Fitness",
    icon: "Dumbbell",
    description: "High-energy workout clips",
    suggestedFilter: "Cool",
    suggestedCaptionStyle: "Bold",
    suggestedMusicMood: "Energetic",
    colorAccent: "#10B981",
  },
  {
    id: "pet-vibes",
    name: "Pet Vibes",
    icon: "PawPrint",
    description: "Adorable pet moments with fun energy",
    suggestedFilter: "Vibrant",
    suggestedCaptionStyle: "Neon",
    suggestedMusicMood: "Fun",
    colorAccent: "#F97316",
  },
  {
    id: "travel",
    name: "Travel",
    icon: "Plane",
    description: "Beautiful travel memories with cinematic warmth",
    suggestedFilter: "Warm",
    suggestedCaptionStyle: "Minimal",
    suggestedMusicMood: "Chill",
    colorAccent: "#3B82F6",
  },
  {
    id: "daily-life",
    name: "Daily Life",
    icon: "Sun",
    description: "Clean, minimal everyday moments",
    suggestedFilter: "None",
    suggestedCaptionStyle: "Minimal",
    suggestedMusicMood: "Upbeat",
    colorAccent: "#8B5CF6",
  },
  {
    id: "gaming",
    name: "Gaming",
    icon: "Gamepad2",
    description: "Bold, high-contrast gaming highlights",
    suggestedFilter: "Noir",
    suggestedCaptionStyle: "Neon",
    suggestedMusicMood: "Energetic",
    colorAccent: "#06B6D4",
  },
  {
    id: "party",
    name: "Party",
    icon: "PartyPopper",
    description: "Vibrant party and celebration clips",
    suggestedFilter: "Vibrant",
    suggestedCaptionStyle: "Bold",
    suggestedMusicMood: "Fun",
    colorAccent: "#EC4899",
  },
  {
    id: "wedding",
    name: "Wedding",
    icon: "Heart",
    description: "Elegant wedding highlights with romantic warmth",
    suggestedFilter: "Warm",
    suggestedCaptionStyle: "Minimal",
    suggestedMusicMood: "Epic",
    colorAccent: "#F9A8D4",
  },
];
