import type { HighlightTemplate } from "./types";

// ── 8 templates ported from iOS TemplateLibrary ──
// Now includes suggestedVelocityStyle and suggestedKineticCaption for full iOS parity.

export const TEMPLATES: HighlightTemplate[] = [
  {
    id: "adventure",
    name: "Adventure",
    icon: "Mountain",
    description: "Epic outdoor moments with cinematic flair",
    suggestedFilter: "Vibrant",
    suggestedCaptionStyle: "Bold",
    suggestedMusicMood: "Epic",
    suggestedVelocityStyle: "hero",
    suggestedKineticCaption: "pop",
    colorAccent: "#F59E0B",
  },
  {
    id: "foodie",
    name: "Foodie",
    icon: "UtensilsCrossed",
    description: "Warm, appetizing food highlights",
    suggestedFilter: "Warm",
    suggestedCaptionStyle: "Classic",
    suggestedMusicMood: "Chill",
    suggestedVelocityStyle: "smooth",
    suggestedKineticCaption: "slide",
    colorAccent: "#EF4444",
  },
  {
    id: "fitness",
    name: "Fitness",
    icon: "Dumbbell",
    description: "High-energy workout clips with beat-synced velocity",
    suggestedFilter: "Cool",
    suggestedCaptionStyle: "Bold",
    suggestedMusicMood: "Energetic",
    suggestedVelocityStyle: "bullet",
    suggestedKineticCaption: "bounce",
    colorAccent: "#10B981",
  },
  {
    id: "pet-vibes",
    name: "Pet Vibes",
    icon: "PawPrint",
    description: "Adorable pet moments with fun energy",
    suggestedFilter: "Vibrant",
    suggestedCaptionStyle: "Neon",
    suggestedMusicMood: "Fun",
    suggestedVelocityStyle: "montage",
    suggestedKineticCaption: "bounce",
    colorAccent: "#F97316",
  },
  {
    id: "travel",
    name: "Travel",
    icon: "Plane",
    description: "Cinematic travel memories with smooth velocity",
    suggestedFilter: "Warm",
    suggestedCaptionStyle: "Minimal",
    suggestedMusicMood: "Chill",
    suggestedVelocityStyle: "smooth",
    suggestedKineticCaption: "slide",
    colorAccent: "#3B82F6",
  },
  {
    id: "daily-life",
    name: "Daily Life",
    icon: "Sun",
    description: "Clean, minimal everyday moments",
    suggestedFilter: "None",
    suggestedCaptionStyle: "Minimal",
    suggestedMusicMood: "Upbeat",
    suggestedVelocityStyle: "montage",
    suggestedKineticCaption: "typewriter",
    colorAccent: "#8B5CF6",
  },
  {
    id: "gaming",
    name: "Gaming",
    icon: "Gamepad2",
    description: "Bold, high-contrast gaming highlights with sharp cuts",
    suggestedFilter: "Noir",
    suggestedCaptionStyle: "Neon",
    suggestedMusicMood: "Energetic",
    suggestedVelocityStyle: "bullet",
    suggestedKineticCaption: "pop",
    colorAccent: "#06B6D4",
  },
  {
    id: "party",
    name: "Party",
    icon: "PartyPopper",
    description: "Vibrant party clips with beat-drop velocity",
    suggestedFilter: "Vibrant",
    suggestedCaptionStyle: "Bold",
    suggestedMusicMood: "Fun",
    suggestedVelocityStyle: "hero",
    suggestedKineticCaption: "pop",
    colorAccent: "#EC4899",
  },
  {
    id: "wedding",
    name: "Wedding",
    icon: "Heart",
    description: "Elegant wedding highlights with romantic warmth",
    suggestedFilter: "Warm",
    suggestedCaptionStyle: "Minimal",
    suggestedMusicMood: "Epic",
    suggestedVelocityStyle: "smooth",
    suggestedKineticCaption: "slide",
    colorAccent: "#F9A8D4",
  },
];
